export const UiTheme = {
  colors: {
    page: '#F5F8FC',
    surface: '#FFFFFF',
    surfaceMuted: '#EAF0F8',
    surfaceElevated: '#FFFFFF',
    border: '#C7D5E8',
    textPrimary: '#0F1E33',
    textSecondary: '#3E536F',
    accent: '#123A73',
    accentSoft: '#DCE7F7',
    accentMuted: '#9AB2D8',
    danger: '#C62828',
    success: '#1B7F3A',
    warning: '#B26A00',
    focusRing: '#123A73',
  },
  spacing: {
    xs: 6,
    sm: 10,
    md: 16,
    lg: 20,
    xl: 24,
    xxl: 32,
  },
  radius: {
    sm: 8,
    md: 12,
    lg: 16,
    xl: 20,
  },
  font: {
    title: 24,
    subtitle: 18,
    body: 14,
    caption: 12,
  },
  typography: {
    display: { fontSize: 32, lineHeight: 36, fontWeight: '900' as const },
    title: { fontSize: 24, lineHeight: 30, fontWeight: '800' as const },
    subtitle: { fontSize: 18, lineHeight: 24, fontWeight: '800' as const },
    body: { fontSize: 14, lineHeight: 20, fontWeight: '600' as const },
    bodyStrong: { fontSize: 14, lineHeight: 20, fontWeight: '800' as const },
    caption: { fontSize: 12, lineHeight: 16, fontWeight: '700' as const },
  },
  shadow: {
    card: {
      shadowColor: '#0F1E33',
      shadowOpacity: 0.08,
      shadowRadius: 14,
      shadowOffset: { width: 0, height: 8 },
      elevation: 3,
    },
    floating: {
      shadowColor: '#0F1E33',
      shadowOpacity: 0.12,
      shadowRadius: 18,
      shadowOffset: { width: 0, height: 10 },
      elevation: 8,
    },
  },
  nav: {
    height: 72,
  },
} as const;
